### ISSUE TITLE
Cannot have more than 30 items in a directory (does not apply to root directory)

### ISSUE THREAD

**Issue by z80andrew** [z80andrew/SerialDisk#8]
`FatAddDirectoryEntry` does not allow directory sizes to be extended beyond a single cluster, so the maximum number of items is 1024/32 - 2 = 30.

**Comment by z80andrew** [comment]
Fixed sector allocation for subdirectories when importing local directory contents.

**Comment by z80andrew** [comment]
Ready for 2.1 release.

**Comment by LaurentChardon** [comment]
I still seem to have this issue with version 2.3.11.0. I try to send some known good files from ST to PC and it crashes after 30 files.
`grep "Saving local file" log/serial_port_error.log  | wc -l`
`30`
Included: verbose log
[serial_port_error.log](https://github.com/z80andrew/SerialDisk/files/5252256/serial_port_error.log)

**Comment by z80andrew** [comment]
I've created a [new bug](https://github.com/z80andrew/SerialDisk/issues/22) for this.  Please see my comments there.
